name: Windows Version Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, windows-2022]  # verschiedene Windows-Versionen testen

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (falls du requirements.txt hast)
        run: |
          if (Test-Path "requirements.txt") {
            pip install -r requirements.txt
          }

      - name: Run tests
        run: |
          python up2date.py
