name: Windows Version Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [Windows-2022, windows-2025, ubuntu-22.04, ubuntu-24.04, macos-latest]  # verschiedene Windows-Versionen testen

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Linux/macOS
      - name: Install dependencies (bash)
        if: runner.os != 'Windows'
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        shell: bash

      # Windows
      - name: Install dependencies (PowerShell)
        if: runner.os == 'Windows'
        run: |
          if (Test-Path "requirements.txt") {
            pip install -r requirements.txt
          }
        shell: pwsh

      - name: Run tests
        run: |
          python up2date.py
